{"uuid": "70b88501-842d-4b45-a67e-dfb887ccde89", "children": ["4f3667a0-e9cf-4ff4-8b76-cacd9e009aca", "4e18a549-71c1-4a05-bcef-7a599fdbddc2"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"/Users/a123/venv/hemei/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/a123/venv/hemei/lib/python3.7/site-packages/_pytest/fixtures.py\", line 938, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/a123/venv/hemei/lib/python3.7/site-packages/_pytest/fixtures.py\", line 799, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/a123/PycharmProjects/hemei/webtestDemo/test_webbaidu_onemodule.py\", line 12, in driver\n    executable_path='/Users/lindafang/PycharmProjects/testframework/excise/driver/chromedriver')\n  File \"/Users/a123/venv/hemei/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"/Users/a123/venv/hemei/lib/python3.7/site-packages/selenium/webdriver/common/service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1557900111140, "stop": 1557900111142}], "start": 1557900111139, "stop": 1557900111391}