{"name": "test_add2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n +  where 4 = add(1, 3)", "trace": "def test_add2():\n        random_value = random.randint(2,10)\n        print(\"random_value:\" +str(random_value))\n>       assert add(1,3) == random_value\nE       assert 4 == 5\nE        +  where 4 = add(1, 3)\n\npytest_demo/test_pytest4.py:13: AssertionError"}, "attachments": [{"name": "log", "source": "66354b4d-07e6-4b34-8868-2aa2b187d0c5-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "e95737a1-42df-4b4b-9f79-7c4c44d4817b-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "7c45f994-6faf-485f-9229-2a7db89e84ca-attachment.txt", "type": "text/plain"}], "start": 1557282962500, "stop": 1557282962500, "uuid": "61d67dab-9dcd-4284-b665-6102ba89e044", "historyId": "0b46107ad32b0abc592d4f90e3375ca8", "fullName": "pytest_demo.test_pytest4#test_add2", "labels": [{"name": "parentSuite", "value": "pytest_demo"}, {"name": "suite", "value": "test_pytest4"}, {"name": "host", "value": "123deMacBook-Pro.local"}, {"name": "thread", "value": "13188-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytest_demo.test_pytest4"}]}